"""Initial schema

Revision ID: 612045ee84cf
Revises: 
Create Date: 2025-12-05 17:18:33.170718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612045ee84cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('scope_rules', sa.JSON(), nullable=False),
    sa.Column('allowed_hosts', sa.JSON(), nullable=False),
    sa.Column('allowed_ports', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_output_path', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('required_approval', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agent_model', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severitylevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('remediation_advice', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cve_ids', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('ai_decisions')
    op.drop_table('scan_jobs')
    op.drop_table('targets')
    # ### end Alembic commands ###
